### ISSUE TITLE
RPC over DDS (RTPS): Multiple subscribers delivery problem

### ISSUE THREAD

**Issue by alekseymt74** [eProsima/RPC#3]
In the example RTPSCalculator I executed multiple (2-10) CalculatorServerExample instances. Then I launch 1 instance of CalculatorClientExample.
Some (2 - always, 3 - maximum) server instances received both 'addition' and 'subtraction', some (1-2) only 'subtraction' and others none of them.
RTPSCalculatorAsync - situation even worse.
I tried this with disabled antivirus/firewall, additional network interfaces - same result.
OS: windows 7 x64
MSVC 2015

I tried both binary distribution and manualy compiled from github.
P.S. As I saw in debugger RTPSProxyProcedureEndpoint::num_matched_sub_ & RTPSProxyProcedureEndpoint::num_matched_pub_ does not match the number of launched server instances.

Thanks!

**Comment by richiware** [comment]
Sorry for the delay @alekseymt74 

This is the expected behaviour. The example you're using only executes two remote procedures. Before sending a request, the client waits to discovery some server. As soon as the client discovers one, it starts to send the remote procedures. When the client finish maybe not all server were discovered yet.

You can modify the example and insert the remote procedure calls inside a **for**. In each iteration call the remote procedures and sleep. You will see in any time all server were discovered and receive the remote procedures.
